# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ spfx-assignment-one-first-iteration ]

# Variables that are available for all the jobs in the workflow
env:
  SPPKG_FILE_NAME: 'spfx-read-write-operations.sppkg'
  DEPLOYMENT_SCRIPT: 'DeployAppToSite.ps1'
  SITE_URL: 'https://bhavyamsdnlego.sharepoint.com/sites/TestExtensionGroupSite2/'
  APP_NAME: 'spfx-read-write-operations4'
  SEND_MAIL: 'true'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains 2 jobs called "build and deploy"  
   build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
      
    # Setup node.js runtime
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    # npm install
    - name: Run npm install
      run: npm install
    
     # install gulp if mac
    - name: Install Gulp if runner is running on MacOS
      run: npm i -g gulp
      if: runner.os == 'macOS'
    
    # gulp build
    - name: Build solution
      run: gulp build
         
    # npm test     
    - name: Test solution
      run: npm test
      
    # gulp bundle and package solution
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship
        
    # upload build package    
    - name: Upload Build Package
      uses: actions/upload-artifact@v2
      with:
        name: buildPackage
        path: sharepoint/solution/${{env.SPPKG_FILE_NAME}}   

    # upload deployment script    
    - name: Upload deployment script
      uses: actions/upload-artifact@v2
      with:
        name: deploymentScript
        path: ${{env.DEPLOYMENT_SCRIPT}}          
   
   # deploy job 
   deploy:
    runs-on: windows-latest
    needs: [build]
    
    steps:
    
    - name: Download package (sppkg file)
      uses: actions/download-artifact@v2
      id: packageDownloadStep
      with:
        name: buildPackage
        path: buildPackage
        
    - name: Download deployment script (ps1 file)
      uses: actions/download-artifact@v2
      with:
        name: deploymentScript 
        path: deploymentScript
        
    - name: Print package download path
      run: echo ${{steps.packageDownloadStep.outputs.download-path}}    
        
    - name: Run script to install PnP Powershell and deploy app on site using PnP Powershell
      run: deploymentScript/${{env.DEPLOYMENT_SCRIPT}} -SiteUrl ${{env.SITE_URL}} -packageFilePath ${{steps.packageDownloadStep.outputs.download-path}}\${{env.SPPKG_FILE_NAME}} -appName ${{env.APP_NAME}} -username ${{secrets.SITECOLLADMINUSERNAME}} -password ${{secrets.SITECOLLADMINPASSWORD}}
      shell: powershell
